#!/usr/bin/env lua

local inspect = require 'inspect'
local argparse = require 'argparse'
local exception = require 'titan-compiler.exception'
local parser = require 'titan-compiler.parser'

local p = argparse(arg[0], 'Titan compiler')
p:argument('input', 'Input file.')
p:flag('--print-ast', 'Print the AST.')
local args = p:parse()

local function get_contents(filename)
    local file = assert(io.open(filename, "r"))
    local contents = file:read("*a")
    file:close()
    return contents
end

local function main()
    local input
    if args.input == '-' then
        input = io.read("*a")
    else
        input = get_contents(args.input)
    end
    local ast = parser.parse(input)
    if args.print_ast then
        print(inspect(ast))
    end
end

local ok, err = exception.try(main)
if not ok then
    print(arg[0] .. ': ' .. tostring(err))
end

